import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../../componets/navbar/Navbar";

import { Inter } from "next/font/google"
// import Navbar from "../components/Navbar"
// import Darkmodetoggle from "../components/Darkmodetoggle/DarkModeToggle"
// import ThemeProvider  from "@/context/ThemeContext"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Etsy Nigera-Shop for handmade, Vintage custom and unigue gifts for everyone",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={sans.className}>{children}</body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {/* <ThemeProvider> */}
          {/* <Darkmodetoggle /> */}
          {/* <Navbar /> */}
          <main>{children}</main>
        {/* </ThemeProvider> */}
      </body>
    </html >
  );
}
